name: Build and upload our custom caddy to S3

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/caddy.yml

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  GO_VERSION: 1.22
  CADDY_VERSION: 2.7.6

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            name: x86_64-unknown-linux-gnu
            goos: linux
            goarch: amd64
          - os: ubuntu-latest
            name: aarch64-unknown-linux-gnu
            goos: linux
            goarch: arm64
          - os: windows-latest
            name: x86_64-pc-windows-gnu
            goos: windows
            goarch: amd64
          - os: macos-14
            name: x86_64-apple-darwin
            goos: darwin
            goarch: amd64
          - os: macos-14
            name: aarch64-apple-darwin
            goos: darwin
            goarch: arm64

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - run: go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
      - run: xcaddy build v${{ env.CADDY_VERSION }} --with github.com/caddy-dns/route53
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
      - shell: bash
        run: |
          ext=""
          [[ "${{ runner.os }}" == windows* ]] && ext=".exe"
          mv caddy$ext caddy-${{ matrix.name }}$ext
      - uses: actions/upload-artifact@v4
        with:
          name: caddy-${{ matrix.os }}
          path: |
            caddy*
            caddy*.exe
          if-no-files-found: error

  upload:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # OIDC token for AWS login
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: caddy-*
          merge-multiple: true

      - name: Sign binaries
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
        run: |
          curl -Lo bestool https://tools.ops.tamanu.io/bestool/gha/${{ runner.os }}-${{ runner.arch }}
          chmod +x bestool
          ./bestool crypto sign --key-env SIGNING_KEY  \
            --comment 'ts={timestamp} repo=${{ github.repository }} commit=${{ github.sha }} gharun=${{ github.run_id }}' \
            caddy-*

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ap-southeast-2
          role-to-assume: arn:aws:iam::143295493206:role/gha-ops-scripts-s3
          role-session-name: GHA@Ops=Caddy

      - name: Upload
        run: |
          for f in caddy-*; do
            aws s3 cp $f s3://bes-ops-tools/caddy/${{ env.CADDY_VERSION }}/$f --no-progress
            aws s3 cp $f s3://bes-ops-tools/caddy/${{ env.CADDY_VERSION }}/$f.sig --no-progress
            aws s3 cp $f s3://bes-ops-tools/caddy/latest/$f --no-progress
            aws s3 cp $f s3://bes-ops-tools/caddy/latest/$f.sig --no-progress
          done
