name: Upload ops web pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/ops-web.yml
      - web/ops/**/*

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  upload:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # OIDC token for AWS login
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ap-southeast-2
          role-to-assume: arn:aws:iam::143295493206:role/gha-ops-scripts-s3
          role-session-name: GHA@Ops=Honeyvent

      - name: Upload
        working-directory: web/ops
        run: |
          aws s3 sync urls s3://bes-ops-tools/urls/
