name: Open mSupply server

on:
  pull_request:
    paths:
      - msupply-server/**
      - .github/workflows/msupply.yml
  push:
    branches:
      - main
    paths:
      - msupply-server/**
      - .github/workflows/msupply.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read
  id-token: write
  attestations: write
  packages: write

env:
  MSUPPLY_VERSION: 2.5.1

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - arch: amd64
            runs-on: ubuntu-24.04
          - arch: arm64
            runs-on: ubuntu-24.04-arm

    runs-on: ${{ matrix.platform.runs-on }}
    steps:
      - name: Verify docker works
        run: docker run hello-world

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup buildkit
        uses: docker/setup-buildx-action@v2

      - uses: docker/metadata-action@v5
        id: meta
        with:
          labels: |
            org.opencontainers.image.title=Open mSupply server
            org.opencontainers.image.url=https://msupply.foundation/open-msupply/
            org.opencontainers.image.source=https://github.com/msupply-foundation/open-msupply
            org.opencontainers.image.version=${{ env.MSUPPLY_VERSION }}
            org.opencontainers.image.licenses=AGPL-3.0

      - name: Build and push
        id: build
        uses: docker/build-push-action@v5
        with:
          context: msupply-server
          file: msupply-server/Dockerfile
          platforms: linux/${{ matrix.platform.arch }}
          cache-from: type=gha,scope=msupply-${{ matrix.platform.arch }}
          cache-to: type=gha,mode=max,scope=msupply-${{ matrix.platform.arch }}
          build-args: MSUPPLY_REF=v${{ env.MSUPPLY_VERSION }}
          push: ${{ github.event_name == 'push' }} # ie to main
          labels: ${{ steps.meta.outputs.labels }}
          tags: ghcr.io/beyondessential/msupply-server:v${{ env.MSUPPLY_VERSION }}.${{ matrix.platform.arch }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ghcr.io/beyondessential/msupply-server:v${{ env.MSUPPLY_VERSION }}.${{ matrix.platform.arch }}
          subject-digest: ${{ steps.build.outputs.digest }}
          push-to-registry: true

  multi-arch:
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    name: Multi-arch image
    steps:
      - name: Install manifest-tool
        run: |
          curl -sLo manifest-tool.tar.gz https://github.com/estesp/manifest-tool/releases/download/v2.1.5/binaries-manifest-tool-2.1.5.tar.gz
          tar -xvf manifest-tool.tar.gz manifest-tool-linux-amd64
          mv manifest-tool-linux-amd64 manifest-tool
          chmod +x manifest-tool

      - name: Combine images
        run: |
          ./manifest-tool push from-args \
            --platforms linux/amd64,linux/arm64 \
            --template ghcr.io/beyondessential/msupply-server:v${{ env.MSUPPLY_VERSION }}.ARCH \
            --target ghcr.io/beyondessential/msupply-server:v${{ env.MSUPPLY_VERSION }}
