name: WAL-G

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/wal-g.yml

permissions:
  id-token: write
  attestations: write

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

env:
  GO_VERSION: "1.20"
  WALG_VERSION: 3.0.0

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            name: x86_64-unknown-linux-gnu
            goos: linux
            goarch: amd64
          - os: Linux-ARM64
            name: aarch64-unknown-linux-gnu
            goos: linux
            goarch: arm64
          - os: windows-latest
            name: x86_64-pc-windows-gnu
            goos: windows
            goarch: amd64
          - os: macos-14
            name: x86_64-apple-darwin
            goos: darwin
            goarch: amd64
          - os: macos-14
            name: aarch64-apple-darwin
            goos: darwin
            goarch: arm64

    runs-on: ${{ matrix.os }}
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
    steps:
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Checkout wal-g source
        uses: actions/checkout@v4
        with:
          repository: wal-g/wal-g
          # use master until new release >3.0.0
          # ref: v${{ env.WALG_VERSION }}

      - name: Install wal-g dependencies
        if: contains(matrix.name, 'linux')
        run: sudo apt install -y curl cmake build-essential
      - name: Install wal-g dependencies
        if: contains(matrix.name, 'darwin')
        run: brew install cmake

      - name: Apply the patch for `backup-push`
        run: |
          cat <<EOF > ./fix-1028-backup-push-connection-cancelled-by-remote-host.patch
          diff --git a/internal/databases/postgres/backup_push_handler.go b/internal/databases/postgres/backup_push_handler.go
          index 3be47a3..8b42d0f 100644
          --- a/internal/databases/postgres/backup_push_handler.go
          +++ b/internal/databases/postgres/backup_push_handler.go
          @@ -582,10 +582,7 @@ func GetPgServerInfo(keepRunner bool) (pgInfo BackupPgInfo, runner *PgQueryRunne
           	tracelog.DebugLogger.Printf("Timeline: %d", pgInfo.Timeline)

           	if !keepRunner {
          -		err = tmpConn.Close()
          -		if err != nil {
          -			return pgInfo, nil, err
          -		}
          +		utility.LoggedClose(tmpConn, "")
           		return pgInfo, nil, err
           	}

          EOF
          git apply fix-1028-backup-push-connection-cancelled-by-remote-host.patch
        shell: bash

      - run: make deps
      - run: make pg_build

      - shell: bash
        run: |
          ext=""
          [[ "${{ matrix.goos }}" == "windows" ]] && ext=".exe"
          # Go doesn't add `exe` extension when building on Windows.
          # https://github.com/golang/go/issues/59790
          mv main/pg/wal-g wal-g-${{ matrix.name }}$ext

      - uses: actions/attest-build-provenance@v1
        with:
          subject-path: wal-g-${{ matrix.name }}*
      - uses: actions/upload-artifact@v4
        with:
          name: wal-g-${{ matrix.name }}
          path: |
            wal-g-${{ matrix.name }}
            wal-g-${{ matrix.name }}.exe
          if-no-files-found: error

  upload:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # OIDC token for AWS login
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: wal-g-*
          merge-multiple: true

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ap-southeast-2
          role-to-assume: arn:aws:iam::143295493206:role/gha-ops-scripts-s3
          role-session-name: GHA@Ops=WalG

      - name: Upload
        run: |
          for f in wal-g-*; do
            aws s3 cp $f s3://bes-ops-tools/wal-g/${{ env.WALG_VERSION }}/$f --no-progress
            aws s3 cp $f s3://bes-ops-tools/wal-g/latest/$f --no-progress
          done

      - name: Clear cache
        run: aws cloudfront create-invalidation --distribution-id=EDAG0UBS1MN74 --paths '/wal-g/*'
